### ISSUE TITLE
[ru] few typos

### ISSUE THREAD

**Issue by KycKyc** [42bytes-team/wfm-localization#25]
![Screenshot from 2020-11-23 15-40-05](https://user-images.githubusercontent.com/12272945/99963019-2db94300-2da2-11eb-9264-ab40f20affd5.png)
![Screenshot from 2020-11-23 15-39-59](https://user-images.githubusercontent.com/12272945/99963024-2e51d980-2da2-11eb-9c8e-c09632ca53c8.png)

**Comment by MrLutik** [comment]
Fixed. Для возможности пользования сайтом, пожалуйста подтвердите вашу учетную запись.
