### ISSUE TITLE
Translate `Heavy Attack Efficiency`

### ISSUE THREAD

**Issue by KycKyc** [42bytes-team/wfm-localization#36]
directory: `/misc`

Done for:
- [ ] de.json
- [x] en.json
- [x] es.json
- [x] fr.json
- [x] it.json
- [ ] ko.json
- [ ] pl.json
- [ ] pt.json
- [ ] ru.json
- [ ] sv.json
- [x] zh-hans.json
- [x] zh-hant,json

**Comment by J0wN** [comment]
Efficienza Attacco Pesante (it)
